// 演示音频：版权曲目仅作占位，播放器演示用（UI 中会标注"演示音频"）
export const DEMO_AUDIOS = [
  "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
  "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
  "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
  "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
  "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
  "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
  "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
  "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
  "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
  "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3",
  "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3",
  "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3",
];

export type ArtistSeed = {
  name: string;
  nameEn: string;
  bio: string;
  birthYear?: number;
  debutYear: number;
  genre: string;
  songs: { title: string; album: string; year: number; duration: number; likes: number; plays: number; demo?: boolean; note: string }[];
};

export const ARTISTS: ArtistSeed[] = [
  {
    name: "许冠杰",
    nameEn: "Sam Hui",
    bio: "粤语流行曲的开山鼻祖，被尊为「歌神」。1970 年代以《鬼马双星》正式确立粤语歌的流行地位，作品以市井百态与草根情怀见长，一手带起「许氏喜剧」与粤语歌时代。",
    birthYear: 1948,
    debutYear: 1967,
    genre: "粤语流行 / 民谣摇滚",
    songs: [
      { title: "浪子心声", album: "半斤八两", year: 1976, duration: 226, likes: 9821, plays: 58200, demo: true, note: "「命里有时终须有，命里无时莫强求」—— 一代港人的处世哲学，洒脱又深情。" },
      { title: "半斤八两", album: "半斤八两", year: 1976, duration: 204, likes: 7640, plays: 44100, note: "唱尽打工仔心酸，草根粤语歌的里程碑之作。" },
      { title: "沧海一声笑", album: "笑傲江湖", year: 1990, duration: 278, likes: 12654, plays: 89900, note: "电影《笑傲江湖》主题曲，豪迈江湖气，粤语与国语皆成经典。" },
      { title: "铁塔凌云", album: "铁塔凌云", year: 1972, duration: 215, likes: 4980, plays: 23300, note: "许冠杰首支粤语创作，香港情怀的起点。" },
    ],
  },
  {
    name: "罗文",
    nameEn: "Roman Tam",
    bio: "香港乐坛殿堂级歌手，声线洪亮华丽，堪称「舞台皇帝」。一曲《狮子山下》传唱数十年，成为香港精神的象征。",
    birthYear: 1945,
    debutYear: 1971,
    genre: "粤语流行 / 电视主题曲",
    songs: [
      { title: "狮子山下", album: "狮子山下", year: 1979, duration: 226, likes: 11320, plays: 77600, note: "港台剧集主题曲，被公认为「香港之歌」，一代人的集体记忆。" },
      { title: "铁血丹心", album: "射雕英雄传", year: 1983, duration: 178, likes: 9340, plays: 66500, demo: true, note: "与甄妮合唱，《射雕英雄传》主题曲，武侠剧金曲之巅。" },
    ],
  },
  {
    name: "林子祥",
    nameEn: "George Lam",
    bio: "香港乐坛「铁肺歌王」，嗓音极具爆发力，作品横跨摇滚与抒情，是少数兼具创作与演唱实力的殿堂级歌手。",
    birthYear: 1947,
    debutYear: 1976,
    genre: "粤语流行 / 摇滚",
    songs: [
      { title: "男儿当自强", album: "电影原声带", year: 1991, duration: 273, likes: 10456, plays: 71000, demo: true, note: "《黄飞鸿》主题曲，改编自古曲《将军令》，大气磅礴的男儿气概。" },
      { title: "分分钟需要你", album: "分分钟需要你", year: 1980, duration: 197, likes: 6890, plays: 33400, note: "甜到入心的情歌，林子祥柔情一面。" },
      { title: "真的汉子", album: "真的汉子", year: 1988, duration: 232, likes: 5210, plays: 28900, note: "热血励志，港式摇滚的代表作。" },
    ],
  },
  {
    name: "谭咏麟",
    nameEn: "Alan Tam",
    bio: "1980 年代香港乐坛「校长」，横跨温拿时代与个人生涯，金曲无数。1980 年代与张国荣的「谭张争霸」成为港乐黄金年代最精彩的篇章。",
    birthYear: 1950,
    debutYear: 1973,
    genre: "粤语流行",
    songs: [
      { title: "讲不出再见", album: "梦幻的笑容", year: 1994, duration: 286, likes: 11200, plays: 78200, demo: true, note: "告别场面的第一神曲，旋律一出，眼泪就忍不住。" },
      { title: "爱情陷阱", album: "爱情陷阱", year: 1985, duration: 213, likes: 8870, plays: 55600, note: "1985 年横扫各大颁奖礼，谭咏麟巅峰时代的代表作。" },
      { title: "一生中最爱", album: "神话1991", year: 1991, duration: 254, likes: 9640, plays: 67300, note: "深情款款，「如真如假，如可分身饰演自己」。" },
      { title: "朋友", album: "暴风女神Lorelei", year: 1985, duration: 268, likes: 7430, plays: 45200, note: "友情颂歌，毕业与欢送场合的必备金曲。" },
    ],
  },
  {
    name: "张国荣",
    nameEn: "Leslie Cheung",
    bio: "香港乐坛与影坛的双栖传奇，「哥哥」。1983 年凭《风继续吹》成名，舞台风格前卫性感，作品跨越流行与艺术，至今仍被深深怀念。",
    birthYear: 1956,
    debutYear: 1977,
    genre: "粤语流行",
    songs: [
      { title: "风继续吹", album: "风继续吹", year: 1983, duration: 296, likes: 13900, plays: 92300, note: "张国荣的成名曲，忧郁深情的港乐经典。" },
      { title: "沉默是金", album: "Hot Summer", year: 1988, duration: 252, likes: 12800, plays: 85600, demo: true, note: "许冠杰作曲、张国荣填词，两人合唱版本亦为经典。" },
      { title: "当年情", album: "Summer Romance", year: 1986, duration: 270, likes: 9340, plays: 61200, note: "电影《英雄本色》主题曲，江湖义气与兄弟情。" },
      { title: "追", album: "宠爱", year: 1994, duration: 294, likes: 8760, plays: 54800, note: "《金枝玉叶》主题曲，「一追再追，只想追赶生命里一分一秒」。" },
    ],
  },
  {
    name: "梅艳芳",
    nameEn: "Anita Mui",
    bio: "香港乐坛「百变天后」，舞台女王。1980 年代以《坏女孩》打破乖乖女形象，是华语乐坛最具舞台魅力的女歌手之一。",
    birthYear: 1963,
    debutYear: 1982,
    genre: "粤语流行",
    songs: [
      { title: "女人花", album: "女人花", year: 1997, duration: 298, likes: 11900, plays: 74500, note: "国语经典，唱尽女性的温柔与坚强。" },
      { title: "夕阳之歌", album: "In Brasil", year: 1989, duration: 245, likes: 8640, plays: 52300, note: "《英雄本色3》主题曲，与《千千阙歌》同曲不同词的双璧。" },
      { title: "似是故人来", album: "The Legend of the Pop Queen", year: 1990, duration: 261, likes: 7890, plays: 46700, demo: true, note: "林夕填词，「恨台上卿卿，或台下我我，不是我跟你」。" },
    ],
  },
  {
    name: "陈百强",
    nameEn: "Danny Chan",
    bio: "香港乐坛「情歌王子」，气质温文尔雅，作品以抒情见长。1980 年代与张国荣、谭咏麟、梅艳芳共同撑起港乐黄金时代。",
    birthYear: 1958,
    debutYear: 1979,
    genre: "粤语流行 / 抒情",
    songs: [
      { title: "一生何求", album: "一生何求", year: 1989, duration: 256, likes: 8720, plays: 57800, note: "电视剧《义不容情》主题曲，「冷暖哪可休，回头多少个秋」。" },
      { title: "偏偏喜欢你", album: "偏偏喜欢你", year: 1983, duration: 201, likes: 9450, plays: 63900, demo: true, note: "旋律缠绵悱恻，陈百强抒情路线的巅峰。" },
      { title: "今宵多珍重", album: "今宵多珍重", year: 1982, duration: 195, likes: 5340, plays: 31200, note: "1979 年老歌翻唱，告别时刻的温柔絮语。" },
    ],
  },
  {
    name: "Beyond",
    nameEn: "Beyond",
    bio: "香港殿堂级摇滚乐队，1983 年成立，主唱黄家驹是华语摇滚的精神图腾。作品以人文关怀与理想主义著称，《海阔天空》是华语世界传唱度最高的摇滚金曲。",
    debutYear: 1983,
    genre: "摇滚 / 流行摇滚",
    songs: [
      { title: "海阔天空", album: "乐与怒", year: 1993, duration: 322, likes: 26500, plays: 186000, demo: true, note: "华语摇滚圣经，「原谅我这一生不羁放纵爱自由」，唱尽追梦人的心声。" },
      { title: "光辉岁月", album: "命运派对", year: 1990, duration: 279, likes: 18700, plays: 129000, note: "为曼德拉而作，人文关怀与摇滚精神的高度统一。" },
      { title: "真的爱你", album: "Beyond IV", year: 1989, duration: 270, likes: 15600, plays: 112000, note: "献给母亲的深情之作，吉他与贝斯的世纪前奏。" },
      { title: "喜欢你", album: "秘密警察", year: 1988, duration: 254, likes: 13400, plays: 96800, note: "黄家驹写给初恋的情歌，粤语情歌的摇滚写法。" },
      { title: "大地", album: "秘密警察", year: 1988, duration: 251, likes: 8930, plays: 64100, note: "Beyond 从地下转为主流的成名作，家国情怀。" },
    ],
  },
  {
    name: "张学友",
    nameEn: "Jacky Cheung",
    bio: "被媒体与歌迷封为「歌神」，唱功公认华语乐坛顶级。1990 年代凭《吻别》红遍全亚洲，唱片销量逾亿，是华语乐坛的商业传奇。",
    birthYear: 1961,
    debutYear: 1984,
    genre: "粤语流行 / 国语流行",
    songs: [
      { title: "每天爱你多一些", album: "情不禁", year: 1991, duration: 275, likes: 10300, plays: 72100, demo: true, note: "改编自桑田佳佑名曲，张学友 90 年代经典之作。" },
      { title: "吻别", album: "吻别", year: 1993, duration: 298, likes: 14800, plays: 104000, note: "国语金曲之王，红遍全球华人世界的爱情悲歌。" },
      { title: "遥远的她", album: "Amour", year: 1985, duration: 296, likes: 7860, plays: 48900, note: "年度十大劲歌金曲，歌神早期代表作。" },
      { title: "分手总要在雨天", album: "真情流露", year: 1992, duration: 284, likes: 6920, plays: 41500, note: "雨夜分手的伤感情歌，港乐经典催泪曲。" },
    ],
  },
  {
    name: "刘德华",
    nameEn: "Andy Lau",
    bio: "香港「四大天王」之一，影坛与歌坛双线称霸三十年。影视金曲与励志歌曲深入人心，是华语世界影响力最大的艺人之一。",
    birthYear: 1961,
    debutYear: 1985,
    genre: "粤语流行 / 国语流行",
    songs: [
      { title: "一起走过的日子", album: "一起走过的日子", year: 1991, duration: 270, likes: 9180, plays: 63400, note: "电影《至尊无上II之永霸天下》主题曲，江湖兄弟情。" },
      { title: "冰雨", album: "爱在刻骨铭心时", year: 1997, duration: 279, likes: 7640, plays: 52800, demo: true, note: "淋着雨等你，国语伤感情歌代表作。" },
      { title: "笨小孩", album: "笨小孩", year: 1998, duration: 248, likes: 5960, plays: 37400, note: "与吴宗宪、柯受良合唱，励志幽默的国民歌曲。" },
    ],
  },
  {
    name: "陈慧娴",
    nameEn: "Priscilla Chan",
    bio: "1980 年代末最受欢迎的女歌手之一，声线清亮甜美。1989 年一曲《千千阙歌》红遍香港，随即赴美留学，留下「告别乐坛」的传奇注脚。",
    birthYear: 1965,
    debutYear: 1984,
    genre: "粤语流行",
    songs: [
      { title: "千千阙歌", album: "永远是你的朋友", year: 1989, duration: 286, likes: 16300, plays: 118000, demo: true, note: "「来日纵是千千阙歌，飘于远方我路上」，告别经典，永不过时。" },
      { title: "飘雪", album: "归来吧", year: 1992, duration: 278, likes: 8940, plays: 61200, note: "游子思念的抒情经典，陈慧娴回归之作。" },
      { title: "傻女", album: "娴情", year: 1988, duration: 238, likes: 6420, plays: 40300, note: "「我恨我共你是线偶」，女人痴情的一曲哀歌。" },
    ],
  },
  {
    name: "王菲",
    nameEn: "Faye Wong",
    bio: "华语乐坛最具个性的天后，声线空灵，风格前卫，横跨粤语与国语市场。从 1990 年代至今影响力不减，是时尚与音乐完美结合的标杆。",
    birthYear: 1969,
    debutYear: 1989,
    genre: "流行 / 另类流行",
    songs: [
      { title: "容易受伤的女人", album: "Coming Home", year: 1992, duration: 260, likes: 9840, plays: 68500, note: "王菲一炮而红的经典，1992 年十大金曲。" },
      { title: "约定", album: "Di-Dar", year: 1997, duration: 274, likes: 11200, plays: 78900, demo: true, note: "林夕填词的经典情歌，「还记得当天旅馆的门牌」。" },
      { title: "红豆", album: "唱游", year: 1998, duration: 245, likes: 13500, plays: 92000, note: "国语国民情歌，「等到风景都看透，也许你会陪我看细水长流」。" },
      { title: "暗涌", album: "玩具", year: 1997, duration: 258, likes: 8210, plays: 53400, note: "压抑而深刻的暗恋情歌，王菲的都市幽怨美学。" },
    ],
  },
  {
    name: "叶倩文",
    nameEn: "Sally Yeh",
    bio: "1980-1990 年代香港乐坛天后，《祝福》《潇洒走一回》等金曲红遍两岸三地，是「潇洒」与「大气」的代名词。",
    birthYear: 1961,
    debutYear: 1980,
    genre: "粤语流行 / 国语流行",
    songs: [
      { title: "祝福", album: "祝福", year: 1988, duration: 249, likes: 7260, plays: 46800, note: "1988 年年度金曲，温暖治愈的离别祝福。" },
      { title: "潇洒走一回", album: "潇洒走一回", year: 1991, duration: 246, likes: 11300, plays: 83100, demo: true, note: "国语神曲，「天地悠悠过客匆匆」，90 年代集体记忆。" },
    ],
  },
  {
    name: "郑秀文",
    nameEn: "Sammi Cheng",
    bio: "香港乐坛天后，90 年代中后期与 2000 年代稳坐女歌手头把交椅，同时是影坛票房女王，形象健康励志。",
    birthYear: 1972,
    debutYear: 1990,
    genre: "粤语流行 / 舞曲",
    songs: [
      { title: "终身美丽", album: "Shocking Pink", year: 2001, duration: 244, likes: 8650, plays: 59300, note: "电影《瘦身男女》主题曲，「因有自信，所以美丽」。" },
      { title: "舍不得你", album: "舍不得你", year: 1995, duration: 282, likes: 5940, plays: 35800, demo: true, note: "Sammi 走红前的粤语代表作。" },
    ],
  },
  {
    name: "陈奕迅",
    nameEn: "Eason Chan",
    bio: "被誉为「香港乐坛最后一个天王」，唱功与选曲俱佳，既有《浮夸》的癫狂，也有《富士山下》的深情，是 2000 年代后港乐的中流砥柱。",
    birthYear: 1974,
    debutYear: 1996,
    genre: "粤语流行 / 国语流行",
    songs: [
      { title: "富士山下", album: "What's Going On...?", year: 2006, duration: 278, likes: 17800, plays: 126000, demo: true, note: "「谁能凭爱意要富士山私有」，林夕哲理性情歌的巅峰。" },
      { title: "浮夸", album: "U87", year: 2005, duration: 276, likes: 15600, plays: 112000, note: "癫狂至极的宣泄，「你当我是浮夸吧」，粤语歌新经典。" },
      { title: "十年", album: "黑白灰", year: 2003, duration: 259, likes: 14200, plays: 101000, note: "国语国民金曲，「十年之前，我不认识你」。" },
      { title: "单车", album: "Shall We Dance? Shall We Talk!", year: 2001, duration: 222, likes: 8940, plays: 64700, note: "写父爱的经典，「如孩儿能伏于爸爸的肩膊」。" },
      { title: "K歌之王", album: "打得火热", year: 2000, duration: 254, likes: 7680, plays: 51200, note: "KTV 时代之歌，「我以为要是唱得用心良苦」。" },
    ],
  },
  {
    name: "容祖儿",
    nameEn: "Joey Yung",
    bio: "2000 年代香港乐坛天后级歌手，获奖无数，现场演唱功力稳定，是英皇娱乐的门面担当。",
    birthYear: 1980,
    debutYear: 1999,
    genre: "粤语流行",
    songs: [
      { title: "我的骄傲", album: "我的骄傲", year: 2003, duration: 248, likes: 8340, plays: 57600, note: "「骄傲」主题励志金曲，2003 年年度十大金曲。" },
      { title: "挥着翅膀的女孩", album: "独照", year: 2003, duration: 244, likes: 9100, plays: 66300, demo: true, note: "国语版国民励志歌，「Believe me I can fly」。" },
      { title: "心淡", album: "我的骄傲", year: 2003, duration: 264, likes: 6120, plays: 39800, note: "林夕执笔的「心淡」三步曲之一，失恋疗伤金曲。" },
    ],
  },
  {
    name: "杨千嬅",
    nameEn: "Miriam Yeung",
    bio: "「大笑姑婆」杨千嬅，以真实率直的个性与感性的情歌深受喜爱，是香港乐坛最具亲和力的天后。",
    birthYear: 1974,
    debutYear: 1996,
    genre: "粤语流行",
    songs: [
      { title: "少女的祈祷", album: "Play It Loud, Kiss Me Soft", year: 2000, duration: 246, likes: 7280, plays: 49800, note: "「沿途与他车厢中私奔般恋爱」，2000 年年度金曲。" },
      { title: "可惜我是水瓶座", album: "Miriam's Music Box", year: 2003, duration: 238, likes: 8450, plays: 58700, demo: true, note: "「要是回去没有止痛药水」，水瓶座自白之歌。" },
      { title: "野孩子", album: "Miriam", year: 2001, duration: 232, likes: 5940, plays: 37200, note: "「朝朝暮暮令我走得多远」，黄伟文代表作。" },
    ],
  },
  {
    name: "李克勤",
    nameEn: "Hacken Lee",
    bio: "1980 年代出道，唱功扎实被誉为「零瑕疵」，历经乐坛起伏仍长红至今，与谭咏麟组「左麟右李」成为演唱会品牌。",
    birthYear: 1967,
    debutYear: 1985,
    genre: "粤语流行",
    songs: [
      { title: "红日", album: "红日", year: 1992, duration: 267, likes: 11200, plays: 79400, demo: true, note: "励志神曲，「命运就算颠沛流离」，全场大合唱必备。" },
      { title: "月半小夜曲", album: "命运符号", year: 1987, duration: 274, likes: 9680, plays: 68200, note: "小提琴前奏一响即是经典，克勤代表作。" },
      { title: "一生不变", album: "Purple Dream", year: 1989, duration: 258, likes: 6180, plays: 41300, note: "电视剧《蓝月亮》主题曲，1989 年十大金曲。" },
    ],
  },
  {
    name: "林忆莲",
    nameEn: "Sandy Lam",
    bio: "华语乐坛天后，唱功细腻、都市情歌深入人心，从粤语黄金年代一路唱到国语乐坛，风格百变。",
    birthYear: 1966,
    debutYear: 1984,
    genre: "粤语流行 / 国语流行 / R&B",
    songs: [
      { title: "至少还有你", album: "林忆莲's", year: 2000, duration: 271, likes: 12400, plays: 86500, demo: true, note: "国语国民情歌，「也许全世界我也可以忘记」。" },
      { title: "爱上一个不回家的人", album: "爱上一个不回家的人", year: 1990, duration: 262, likes: 7920, plays: 54600, note: "都市女性情歌经典，1990 年国语专辑大卖。" },
      { title: "伤痕", album: "Love, Sandy", year: 1995, duration: 276, likes: 7060, plays: 46700, note: "李宗盛制作的疗伤情歌，成熟女人的心路。" },
    ],
  },
  {
    name: "谢安琪",
    nameEn: "Kay Tse",
    bio: "2000 年代末的「草根天后」，作品关注社会百态，《喜帖街》唱出了城市变迁的集体记忆。",
    birthYear: 1977,
    debutYear: 2005,
    genre: "粤语流行",
    songs: [
      { title: "喜帖街", album: "Binary", year: 2008, duration: 284, likes: 10900, plays: 74800, demo: true, note: "以利东街清拆为背景，唱尽时代变迁与告别，2008 年度之歌。" },
      { title: "钟无艳", album: "3/8", year: 2007, duration: 256, likes: 6740, plays: 43800, note: "「你待我好，好到可痛吗」—— 备胎之歌的巅峰之作。" },
    ],
  },
  {
    name: "古巨基",
    nameEn: "Leo Ku",
    bio: "1990 年代出道的实力唱将，声线深情，《爱与诚》《情歌王》等作品传唱度高，是情歌市场的中坚力量。",
    birthYear: 1972,
    debutYear: 1994,
    genre: "粤语流行",
    songs: [
      { title: "爱与诚", album: "大雄", year: 2004, duration: 248, likes: 7260, plays: 48700, demo: true, note: "「别再做情人，做只猫做只狗」，2004 年年度金曲。" },
      { title: "情歌王", album: "劲歌金曲", year: 2005, duration: 785, likes: 6480, plays: 42900, note: "32 首情歌串烧而成，KTV 必点神曲。" },
    ],
  },
];

export const EVENTS: { decade: number; year: number; title: string; content: string }[] = [
  { decade: 1970, year: 1971, title: "许冠杰率莲花乐队爆红", content: "许冠杰与莲花乐队登上电视节目《双星报喜》，奠定粤语流行歌走向大众的开端。" },
  { decade: 1970, year: 1974, title: "《鬼马双星》开创粤语歌先河", content: "同名唱片销量超过15万，粤语流行曲自此确立商业地位，被视为港乐元年。" },
  { decade: 1970, year: 1976, title: "《半斤八两》横扫乐坛", content: "首张粤语唱片创下惊人销量，草根粤语歌成为时代主声。" },
  { decade: 1970, year: 1979, title: "《狮子山下》唱响全港", content: "罗文演唱的《狮子山下》成为香港精神的代名词，此后数十年反复传唱。" },
  { decade: 1980, year: 1981, title: "十大中文金曲颁奖礼首办", content: "香港电台创办《十大中文金曲》，华语乐坛第一个正式颁奖礼诞生。" },
  { decade: 1980, year: 1983, title: "张国荣《风继续吹》成名", content: "一曲《风继续吹》让张国荣红遍乐坛，港乐进入群星并起的年代。" },
  { decade: 1980, year: 1984, title: "十大劲歌金曲颁奖礼诞生", content: "无线电视创办《十大劲歌金曲》，与十大中文金曲并列为乐坛最高荣誉。" },
  { decade: 1980, year: 1985, title: "谭张争霸拉开序幕", content: "谭咏麟《爱情陷阱》大热，与张国荣的良性竞争推动港乐进入最辉煌的十年。" },
  { decade: 1980, year: 1986, title: "梅艳芳「百变」成风", content: "梅艳芳以百变形象与舞台魅力成为乐坛大姐大，女歌手地位空前。" },
  { decade: 1980, year: 1988, title: "Beyond《大地》走红", content: "摇滚乐队 Beyond 凭《大地》从地下走向主流，港式摇滚迎来高光。" },
  { decade: 1980, year: 1989, title: "陈慧娴《千千阙歌》告别", content: "一曲《千千阙歌》成为年度金曲，陈慧娴随即赴美留学，留下乐坛传奇。" },
  { decade: 1980, year: 1989, title: "谭咏麟宣布退奖", content: "谭咏麟在颁奖礼上宣布不再领取竞争性奖项，「谭张争霸」逐渐落幕。" },
  { decade: 1990, year: 1990, title: "《光辉岁月》致敬曼德拉", content: "Beyond 以《光辉岁月》向争取自由的南非领袖致敬，摇滚与人文情怀同辉。" },
  { decade: 1990, year: 1991, title: "四大天王正式封号", content: "媒体封张学友、刘德华、黎明、郭富城为「四大天王」，偶像工业达到巅峰。" },
  { decade: 1990, year: 1993, title: "《海阔天空》与家驹离世", content: "Beyond 发表《海阔天空》，黄家驹同年意外离世，华语摇滚痛失精神领袖。" },
  { decade: 1990, year: 1993, title: "《吻别》红遍亚洲", content: "张学友国语专辑《吻别》全亚洲销量破四百万，奠定「歌神」地位。" },
  { decade: 1990, year: 1994, title: "张国荣复出歌坛", content: "淡出乐坛数年后的张国荣复出，红馆演唱会一票难求，艺术形象再登高峰。" },
  { decade: 1990, year: 1996, title: "《友情岁月》掀起古惑仔热", content: "郑伊健《友情岁月》随电影《古惑仔》红极一时，港产片与港乐互相成就。" },
  { decade: 1990, year: 1998, title: "红馆演唱会文化鼎盛", content: "1990 年代末，红磡体育馆成为华语演唱会圣地，港乐影响辐射全亚洲。" },
  { decade: 2000, year: 2000, title: "陈奕迅《K歌之王》登基", content: "「K歌之王」让陈奕迅奠定新一代天王的地位，港乐完成世代交接。" },
  { decade: 2000, year: 2001, title: "郑秀文影视歌三栖称霸", content: "《终身美丽》随电影《瘦身男女》大热，Sammi 成为新一代天后。" },
  { decade: 2000, year: 2003, title: "一代巨星陨落", content: "张国荣与梅艳芳先后离世，香港乐坛经历最沉痛的一年，全港同哀。" },
  { decade: 2000, year: 2003, title: "容祖儿《我的骄傲》登顶", content: "《我的骄傲》横扫当年颁奖礼，容祖儿成为英皇年代的女歌手代表。" },
  { decade: 2000, year: 2006, title: "《富士山下》封神", content: "陈奕迅《富士山下》集词曲唱于大成，被视为粤语情歌新高度。" },
  { decade: 2000, year: 2008, title: "《喜帖街》唱尽城市记忆", content: "谢安琪《喜帖街》以利东街清拆为背景，成为年度之歌与时代之声。" },
  { decade: 2010, year: 2010, title: "唱片业寒冬与数字革命", content: "实体唱片式微，港乐在数字化浪潮中摸索转型，四大唱片与电视版权之争成为焦点。" },
  { decade: 2010, year: 2015, title: "「广东歌」复兴呼声", content: "黄伟文作品展演唱会一票难求，乐迷重燃对粤语歌的热情，「广东歌永不会死」成为口号。" },
  { decade: 2020, year: 2020, title: "林家谦《一人之境》爆红", content: "新一代唱作人林家谦走红，港乐新血涌动，独立与流行边界日益模糊。" },
  { decade: 2020, year: 2021, title: "MIRROR 现象席卷全港", content: "男团 MIRROR 人气爆棚，港乐与偶像文化迎来新一轮高峰，红馆一票难求。" },
];
